---
- name: install vagrant plugins
  shell: vagrant plugin install {{item}}
  with_items:
    - vagrant-proxyconf
    - vagrant-hostsupdater
    - vagrant-cachier
    - vagrant-mutate
    - vagrant-libvirt
    - vagrant-smartos-zones
    
